library(sqldf)
data<-read.csv.sql("household_power_consumption.txt",sql="select * from file where Date in ('1/2/2007','2/2/2007')",sep=";")
data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
with(data,{
        plot(Date,Global_active_power,type="l",xlab="",ylab="Global Active Power")
        plot(Date,Voltage,type="l",xlab="datetime")
        plot(Date,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
        lines(Date,Sub_metering_2,type="l",col="red")
        lines(Date,Sub_metering_3,type="l",col="blue")
        legend("topright",bty="n",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
        plot(Date,Global_reactive_power,type="l",xlab="datetime")
})
dev.copy(png,file="plot4.png")
dev.off()